#!/bin/bash 

while :
do
echo "Please input case: "
read Keypress 

    rm -rf ./pro/*

	case "$Keypress" in
		"fcfs" ) 
			./start fcfs& ;;
		"rr" )
			./start rr 1& ;;
		"spn" )
			./start spn& ;;
		"fb" )
			./start fb 1& ;;
		"srt" )
			./start srt& ;;
		"hrrn" )
			./start hrrn& ;;
		"exit" )
			echo "Show over!"
			break ;;
		* )
			echo "Try it again!" 
			continue
	esac

	for((i=1;i<=5;i=$i+1))
	do
		cp ./show/pro$i ./pro
		sleep 2.00
	done
	sleep 15.00
	kill %1

done
exit 0

